#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('profile', ['full', 'iterate', 'build', 'run']):

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-viewer-role-binding
subjects:
- kind: User
  name: mrrabayata@vmware.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: jeffa2@vmware.com
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: the-mister-rabayata-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: app-viewer
  apiGroup: rbac.authorization.k8s.io
