apiVersion: v1
kind: ServiceAccount
metadata:
  name: default #! use value from "Install Default Supply Chain"
secrets:
  - name: registry-credentials
  - name: git-ssh
imagePullSecrets:
  - name: tap-registry
  - name: registry-credentials