apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scanner-dotnet
  labels:
    apps.tanzu.vmware.com/sonarqube: "sonarqube"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: "sonarqube scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  params:
    - name: sonar-host-url
      description: Host URL where the sonarqube server is running
      default: ""
    - name: sonar-project-key
      description: Project's unique key
      default: ""
    - name: sonar-token
      description: Auth for the project
      default: ""
    - name: source-url
      description: Location of the source code
    - name: source-revision
      description: i.e. git hash
      default: ""
    - name: wait-on-sonar-analysis
      description: toggle to wait until sonarqube analysis is complete
    - name: source-sub-path
      default: ""

  workspaces:
    - name: supplychain-workspace

  steps:
    - name: pull-code
      image: gradle
      workingDir: $(workspaces.supplychain-workspace.path)
      script: |
        #!/usr/bin/env bash
        set -ex
        wget -qO- $(params.source-url) | tar xvz

    - name: sonar-scan
      image: mcr.microsoft.com/dotnet/sdk:6.0
      workingDir: $(workspaces.supplychain-workspace.path)
      script: |
        apt-get update
        apt-get install --yes openjdk-11-jre
        dotnet tool install --global dotnet-sonarscanner
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet sonarscanner begin /k:$(params.sonar-project-key) /d:sonar.host.url=$(params.sonar-host-url) /d:sonar.login=$(params.sonar-token) /d:sonar.qualitygate.wait=$(wait-on-sonar-analysis)
        dotnet build *.sln
        dotnet sonarscanner end /d:sonar.login=$(params.sonar-token)