#@data/values
---
registry:
  server:
  repository:
  ca_cert_data: ""

maven:
  repository:
    url: "https://repo.maven.apache.org/maven2"
    secret_name:

gitops:
  repository_prefix:
  branch: main
  username: supplychain
  email: supplychain
  commit_message: supplychain@cluster.local
  ssh_secret: ""
  commit_strategy: direct
  server_address:
  repository_owner:
  repository_name:
  pull_request:
    server_kind:
    commit_branch: ""
    pull_request_title:
    pull_request_body:

scanning:
  source:
    policy: scan-policy
    template: blob-source-scan-template
  image:
    policy: scan-policy
    template: private-image-scan-template

cluster_builder: default
service_account: default
git_implementation: go-git
external_delivery: false

supported_workloads:
- type: web
  cluster_config_template_name: config-template
- type: server
  cluster_config_template_name: server-template
- type: worker
  cluster_config_template_name: worker-template