#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: canary
subjects:
- kind: ServiceAccount
  name: default
  namespace: #@ data.values.name