#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  annotations: 
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ data.values.imported.ssh_privatekey
  identity: #@ data.values.imported.ssh_privatekey
  known_hosts: #@ data.values.imported.known_hosts