apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: api-gateway
  labels:
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8090"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.name: api-gateway
spec:
  count: 1
  observability:
    metrics:
      prometheus:
        enabled: true
  serviceAccount:
    name: gateway-sa
  extensions:
    secretsProviders:
      - name: vault-api-keys
        vault:
          roleName: gateway-role
          path: api-portal-for-vmware-tanzu
    filters:
      apiKey:
        enabled: true
        secretsProviderName: vault-api-keys