#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: scg-ingress
spec:
  virtualhost:
    fqdn: #@ data.values.name + "-gateway.run.prep.tapsme.org"
    tls:
      secretName: scg-ingress-cert
  routes:
  - services:
    - name: api-gateway
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scg-ingress-cert
spec:
  subject:
    countries:
    - US
    provinces:
    - California
    localities:
    - San Fransisco
    organizations:
    - vmware
    organizationalUnits:
    - vmware mambg
  secretName: scg-ingress-cert
  isCA: false
  dnsNames:
  - #@ data.values.name + "-gateway.run.prep.tapsme.org"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io