apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "0m"
  target:
    name: registry-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .workloadregistry | toString }}"
  data:
    - secretKey: workloadregistry
      remoteRef: 
        key: dev/tap-build/tap/tenant-install-secrets
        property: workloadregistry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  toNamespaces:
  - "*"