apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workload-git-ssh
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install-secrets
    kind: SecretStore
  refreshInterval: "0m"
  target:
    type: kubernetes.io/ssh-auth
  data:
  - secretKey: known_hosts
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: known_hosts
  - secretKey: ssh-privatekey
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: ssh-privatekey
  - secretKey: identity
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: ssh-privatekey
    