apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workload-git-ssh
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install-secrets
    kind: SecretStore
  refreshInterval: "0m"
  target:
    name: workload-git-ssh
    template:
      type: Opaque
      metadata:
        annotations: 
          tekton.dev/git-0: github.com
      data:
        ssh-privatekey: "{{ .private_key | b64dec }}"
  data:
  - secretKey: private_key
    remoteRef:
      key: dev/tap-build/tap/tenant-install-secrets
      property: private_key